### ISSUE TITLE
Webpack "Can't resolve 'fs' in index.js"

### ISSUE THREAD

**Issue by dseeker** [commenthol/ua-parser2#11]
When using webpack to compile a browser application, I'm getting:
```
"Can't resolve 'fs' in index.js"
@ ./node_modules/ua-parser2/js/index.js 4:7-20
```

**Comment by commenthol** [comment]
Hi,
this library does not aim to run in a browser env.
Basically the size of the regexes file is not considered well suited for this purpose. There are other libs on npm which should fill this gap, maybe on cost of accuracy.
Anyhow in case you like to insist getting things done with webpack, I can recommend the node setting. See https://webpack.js.org/configuration/node/

**Comment by dseeker** [comment]
Thanks for the feedback, I’ll do that
