### ISSUE TITLE
Error: Function yaml.safeLoad

### ISSUE THREAD

**Issue by jeyanthimayil** [commenthol/ua-parser2#12]
Hi,
    I'm facing the below error while using **ua-parser2** module.

  **Error**: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.

 Updated  line no:158  **(regexes = yaml.safeLoad(contents))** to  **(regexes = yaml.load(contents) )** in index.js. Now it's working fine. Please fix this issue ASAP.  

![image](https://user-images.githubusercontent.com/17119054/103636041-6cc8df80-4f6f-11eb-8eef-a31877026775.png)

**Comment by commenthol** [comment]
Hi @jeyanthimayil , Yes the package needs an update. If travis tests are passing you'll find an update soon on npm.
