### ISSUE TITLE
Lower vs Uppercase OS

### ISSUE THREAD

**Issue by chhams** [commenthol/ua-parser2#13]
Hi, 

When the OS is lowercase it is sometimes not correctly identified, here is an example where just one letter if different in casing:

```
var uaParser = require('ua-parser2')();
var res;
var uaLowerOs = "mozilla/5.0 (linux; android 7.1.0; sgp712 build/32.4.a.) applewebkit/537.36 (khtml, like gecko)";
var uaUpperOs = "mozilla/5.0 (linux; Android 7.1.0; sgp712 build/32.4.a.) applewebkit/537.36 (khtml, like gecko)";

res = uaParser.parse(uaLowerOs);
console.log(res.os); //OS "Other"

res = uaParser.parse(uaUpperOs);
console.log(res.os); //OS correctly Android
```

On other useragents it works... Do you have an explanation for that?

**Comment by commenthol** [comment]
Hi, this library parses user-agent strings case sensitive. So changing your user-agent strings to lowercase before parsing them with this package is not recommended.
