### ISSUE TITLE
Merge into uap-core?

### ISSUE THREAD

**Issue by mrjgreen** [commenthol/ua-parser2#2]
Hey, lots of these improvements look like they could be integrated into the core without breaking BC. I really like the type attribute on the agent. Have you ever tried to get them merged in?

**Comment by commenthol** [comment]
Hi @mrjgreen, Thanks for your request. To be honest the type attribution is quite new in uaparser2, basically I started to work on performance first, introducing regex groups. The type attribution was just the next step.
I definitely like to take things a step further, as I am working on a new version which will definitely break the device parsing. It is nearly impossible to have proper device attribution for Android as the device fragmentation is so heavy there without any massive impact on performance.
You can feel free to backport things of this project to uap-core.
