### ISSUE TITLE
Yaml Exception - duplicated mapping key

### ISSUE THREAD

**Issue by Cadey** [commenthol/ua-parser2#4]
Hi,

We have just (over night) had our servers throw exceptions using the default yaml file in ua-parser2.

It appears the yaml file has some duplicate keys and so needs to be loaded with the option "json : true"

**Comment by Cadey** [comment]
its possible that the js-yaml have recently updated and caused this ?

ua-parser2 is requesting js-yaml >= 3.4.2 and its possible the update to 3.5.X caused this?

**Comment by commenthol** [comment]
Nope, no recent update. The last one is from `'0.1.31': '2015-11-24T21:24:34.786Z'`
Yes you are right, the update to js-yaml@3.5 causes the problem.

**Comment by commenthol** [comment]
ua-parser2@0.1.32 is out right now - issue should be fixed. Thanks for reporting.

**Comment by Cadey** [comment]
cool, thanks for the quick update :+1:
