### ISSUE TITLE
Classify Web Monitoring Agents as bots (or at least as Web Monitoring Agents)

### ISSUE THREAD

**Issue by oronjaco** [commenthol/ua-parser2#7]
There are few monitoring agents that identify themselves through the useragent header.
We should be able to classify them as bots.
For example: Keynote adding 'KTXN' at the end of the UA.

https://answers.dynatrace.com/questions/158192/how-can-i-exclude-traffic-from-keynote-agents.html
http://www.keynote.com/resources/blog/2015/june/how-to-block-web-monitoring-agents-from-web-analytics

**Comment by commenthol** [comment]
For `gomezagent, ruxitsynthetic, ktxn` I have User-Agent samples here to create the regexes.
With `apm synthetic agent, khte, ktht, dynatrace` I would need your help in providing me with a real User-Agent Strings for each.

**Comment by commenthol** [comment]
Closing...
